### ISSUE TITLE
Error: Input must be a vector, not a `tbl_df/tbl/data.frame/synth_tbl` object.

### ISSUE THREAD

**Issue by christopherdavisw** [edunford/tidysynth#1]
Error when attempting to run the test code in the README. Specifically, the `generate_predictor()` function throws an error: "Error: Input must be a vector, not a `tbl_df/tbl/data.frame/synth_tbl` object."

**Comment by edunford** [comment]
Thanks for pointing this out, @cdavisurban! The package was using an arbitrary class `synth_tbl` as a method for ensuring objects in the synth pipeline were correctly formatted. However, it seems with the latest versions of the tidyverse (on which the entire package is built), there are stricter error warnings placed on `tbl_df` objects with an additional class assignment not recognize by the tidy functions. 

To fix the issue, I removed the `synth_tbl` class type from the package infrastructure. The objects outputted from the synth pipeline now operate as standard `tbl_df` objects. This means you can interact with them as you would any nest tibble or use the `grab_` prefix functions as outlined in the read me to access specific data values.

**Comment by christopherdavisw** [comment]
Thanks so much @edunford! I just ran through the updates and they look great. Thanks so much for writing this package, contributing to the community, and for being so responsive! This will be super useful for us when running synthetic control methods!

Thanks again!
