### ISSUE TITLE
"grab_signficance" typo when installed from CRAN

### ISSUE THREAD

**Issue by alexmarsella** [edunford/tidysynth#11]
This package is excellent. Thank you so much for putting in the time to make this,  it saved me from an error that was plaguing my Synth usage for months now. Error aside, it is much easier and faster than Synth, especially for placebos. 

When I try to implement `grab_significance`, it does not recognize it. Typo in the package wants `grab_signficance`. Thought I would bring that to your attention. To be clear, I installed the package from CRAN with R's built-in installer.

**Comment by edunford** [comment]
Ah thank you for pointing this out. It's a known issue (https://github.com/edunford/tidysynth/issues/3). The latest dev version resolves if (i.e. downloading the package version from github). The fix can be found here 0389f29937b539. Though I still need to update the CRAN version. Thank you for using and please let me know if you find any other spelling errors! Unfortunately in my haste these things happen...
