### ISSUE TITLE
grab_significance function not found

### ISSUE THREAD

**Issue by accesstomedicines** [edunford/tidysynth#15]
Hello-- thanks for the great package. I'm getting the following error message:

Error in grab_significance(.) :  could not find function "grab_significance"

Thanks for any help.

**Comment by edunford** [comment]
Ah yes, sorry about that. This is due to a typo in the cran version (see https://github.com/edunford/tidysynth/issues/11). Pushing a new version of the package to cran now that will bring an end to this misspelling madness. Thanks for using the package!
