### ISSUE TITLE
One-tailed permutation tests

### ISSUE THREAD

**Issue by aneeman** [edunford/tidysynth#23]
Thanks for this wonderful tool! I have a quick question: I'm running a synthetic control in which the plausible treatment effects are almost certainly negative. With that in mind, I'd like to modify the permutation test to be one-tailed rather than two-tailed. Do you know of a good way to do this, either via tidysynth or another SCM package? I can't seem to find anything, but it seems like a need that would come up frequently enough to be worth making available, if not already.

**Comment by edunford** [comment]
Thanks for reaching out! So technically all the data you'd need to compute a one-tailed test is accessible via the relevant `grab_` functions (i.e. to get the synthetic controls for each of units both from the treated and donor pool). Post what you end up cooking up here!
