### ISSUE TITLE
System is computationally singular

### ISSUE THREAD

**Issue by christopherdavisw** [edunford/tidysynth#24]
Does anyone have thoughts on how to solve the "system is computationally singular" error? I get this error when running synth commands with multiple predictors. 

I think it's something in the `synth_method` function, and seems to throw an error for some geographic observations and not others when using `generate_placebos = TRUE`

**Comment by edunford** [comment]
Interesting @cdavisurban! Could you provide a reproducible example so I can try to simulate the error? I haven't run into this before.
