### ISSUE TITLE
Multiple treatment units

### ISSUE THREAD

**Issue by allyshac** [edunford/tidysynth#25]
Hello,

My apologies if this is not the right place to ask this, but I was wondering if we are able to use this package for multiple treatment units yet? I know it's something that was in the works but wanted to check to see if it is implementable yet. 

Thank you!

**Comment by edunford** [comment]
Ah unfortunately, it is not. Though I'm more than happy to review a PR if you've been toying around an implementation! We'll get it incorporated into the stack if it's stable enough.
