### ISSUE TITLE
Package was removed from CRAN

### ISSUE THREAD

**Issue by pozlepster** [edunford/tidysynth#26]
Hi, 

thank you for developing this wonderful package, it really makes it very easy and fast to implement the synthetic control method. :) In case you did not yet notice, I just wanted to highlight that today the package was archived/removed from CRAN as it: "requires archived package 'LowRankQP' ". I noticed that the same problem occurred with Synth package. I hope it will be possible to get the packages back to CRAN. 

Thanks again for all your hard work with the package

**Comment by Tofunmi19** [comment]
Hi,

I just wanted to bring this to your attention. Really appreciate your help on this great package. Would be nice to have it back up again.

Thanks.

**Comment by Tofunmi19** [comment]
Just making an update here for anyone that runs into this issue. I was able to figure this out by downloading and installing the archived version of this package from CRAN, alongside all its dependencies. Thanks!

**Comment by edunford** [comment]
Hi @pozlepster and @Tofunmi19! Thank you both for reaching out and sorry for the delay! I'm trying to work through a work around with `LowRankQP` down. Mainly, working on just building out this method natively in `tidysynth` (but also somewhat hoping that the owners of the package might submit a patch soon).

**Comment by edunford** [comment]
Happy to report that I was able to resolve the issue. The developer version of the package works now and updating the submission to CRAN to get it back up and running. Thanks for your patience!
