### ISSUE TITLE
grab_signficance time range error

### ISSUE THREAD

**Issue by gloriadli** [edunford/tidysynth#4]
When specifying an incorrect time frame,`grab_signficance()` throws the following error. In the example below, 1993 is the intervention time, thus the range does not include post-intervention data.

![image](https://user-images.githubusercontent.com/57513903/115560259-680c0b00-a282-11eb-8278-c2485ae7f949.png)

This can be replicated using the example in the readme using the following date range: `smoking_out %>% grab_signficance(1970:1988)`.

Thanks Dr. Dunford!

**Comment by edunford** [comment]
Thanks again for pointing this bug out, Gloria! I've now added a check that ensures their are post-treatment observations when running grab_significance(). (afd112a57)
